trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    repository: 'mauroelpatiodemiabuela'
    command: 'buildAndPush'
    Dockerfile: 'ApiRestaurante2/Dockerfile'
    buildContext: '.'
    tags: |
      $(Build.BuildId)
      latest